version: '3.8'


services:
  db_kc:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - "5432:5432"
    networks:
      - app-net
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
      DB_VENDOR: POSTGRES
      DB_ADDR: db_kc
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
    ports:
      - "8181:8080"
    depends_on:
      - db_kc
    networks:
      - app-net
  db_app:
    image: postgres:latest
    environment:
      POSTGRES_DB: coruja_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1243
    ports:
      - "5443:5432"
    networks:
      - app-net
      

networks:
  app-net:
    driver: bridge
