#schoolcall
server:
  port: 8000

# Configuration for PostgreSQL Database
spring:
  application:
    name: sga_coruja
  datasource:
    url: jdbc:postgresql://localhost:5443/coruja_db
    username: root
    password: 1243
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5443/coruja_db
    user: root
    password: 1243
